spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

app:
  jwt:
    secret: dGVzdFNlY3JldEtleUZvclVuaXRUZXN0aW5nT25seU5vdFByb2R1Y3Rpb24=
    expiration-ms: 3600000
